name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: image to build and publish
        required: true
        options:
          - alpine
          - barman
          - jdk
          - jre
          - pgpool
          - postgres
      version:
        required: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.inputs.image }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{ defaultContext }}:${{ github.event.inputs.image }}"
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: viascom/${{ github.event.inputs.image }}:${{ github.event.inputs.version }}